[package]
name = "test-statically-disable"
version = "0.0.1"
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
readme = "README.md"
publish = false

[dependencies]
fastrace = { workspace = true }
