[package]
name = "fastrace-opentelemetry"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "Opentelemetry reporter for fastrace"
documentation = "https://docs.rs/fastrace-jaeger"
readme = "README.md"
categories = ["development-tools::debugging"]
keywords = ["tracing", "span", "datadog", "jaeger", "opentelemetry"]

[dependencies]
fastrace = { workspace = true }
futures = { version = "0.3", features = ["executor"] }
log = "0.4"
opentelemetry = { version = "0.23", features = ["trace"] }
opentelemetry_sdk = { version = "0.23", features = ["trace"] }

[dev-dependencies]
opentelemetry-otlp = { version = "0.16", features = ["trace"] }
rand = "0.8"
tokio = { version = "1", features = ["rt-multi-thread"] }
